// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateReleased")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PersonalId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("PositionId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1990, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            Gender = "Male",
                            LastName = "Doe",
                            PersonalId = "19001304662",
                            PhoneNumber = "941293812",
                            PositionId = 1,
                            Status = "Regular"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1890, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Grisha",
                            Gender = "Male",
                            LastName = "Oniani",
                            PersonalId = "18001304662",
                            PhoneNumber = "911293812",
                            PositionId = 3,
                            Status = "NonRegular"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1690, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateReleased = new DateTime(2021, 3, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            FirstName = "Badri",
                            Gender = "Male",
                            LastName = "Shubladze",
                            PersonalId = "18071304662",
                            PhoneNumber = "941293312",
                            PositionId = 1,
                            Status = "Released"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2018, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateReleased = new DateTime(2021, 3, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            FirstName = "Greta",
                            Gender = "Female",
                            LastName = "Thunberg",
                            PersonalId = "18071304772",
                            PhoneNumber = "941290312",
                            PositionId = 3,
                            Status = "Released"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(2008, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "C",
                            Gender = "Male",
                            LastName = "Sharp",
                            PersonalId = "18071304102",
                            PhoneNumber = "941294312",
                            PositionId = 1,
                            Status = "Regular"
                        });
                });

            modelBuilder.Entity("Core.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Developer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Designer"
                        });
                });

            modelBuilder.Entity("Core.Entities.Employee", b =>
                {
                    b.HasOne("Core.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });
#pragma warning restore 612, 618
        }
    }
}
